### ISSUE TITLE
Hungarian language

### ISSUE THREAD

**Issue by dobakszilard** [trollix/ha-tsmoon-card#2]
Hello, I created the Hungarian language, would you please add it?
[hu.json](https://github.com/user-attachments/files/16171837/hu.json)

**Comment by trollix** [comment]
Hello,
Hungarian language added in 0.8.50. Thanks for your help

**Comment by trollix** [comment]
Hello,
Hungarian language added in 0.8.50. Thanks for your help

**Comment by dobakszilard** [comment]
could you add localize.ts?
